// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaooQ8f4kmGWkJ9e3I0bsvsAZmt6YhNco',
    appId: '1:997210914530:web:0d6e83653155eb36fda8bb',
    messagingSenderId: '997210914530',
    projectId: 'teste-6de58',
    authDomain: 'teste-6de58.firebaseapp.com',
    databaseURL: 'https://teste-6de58-default-rtdb.firebaseio.com',
    storageBucket: 'teste-6de58.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIBIYKg4TMz2r8Kb2auAH4R6ogTsHfO_A',
    appId: '1:997210914530:android:16f4ef9b413eef43fda8bb',
    messagingSenderId: '997210914530',
    projectId: 'teste-6de58',
    databaseURL: 'https://teste-6de58-default-rtdb.firebaseio.com',
    storageBucket: 'teste-6de58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFAcPY6dcc8Oo8J9bT8B3NdzP_1F7ESkM',
    appId: '1:997210914530:ios:bfdedcc707164c2ffda8bb',
    messagingSenderId: '997210914530',
    projectId: 'teste-6de58',
    databaseURL: 'https://teste-6de58-default-rtdb.firebaseio.com',
    storageBucket: 'teste-6de58.firebasestorage.app',
    iosBundleId: 'com.example.teste12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFAcPY6dcc8Oo8J9bT8B3NdzP_1F7ESkM',
    appId: '1:997210914530:ios:bfdedcc707164c2ffda8bb',
    messagingSenderId: '997210914530',
    projectId: 'teste-6de58',
    databaseURL: 'https://teste-6de58-default-rtdb.firebaseio.com',
    storageBucket: 'teste-6de58.firebasestorage.app',
    iosBundleId: 'com.example.teste12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaooQ8f4kmGWkJ9e3I0bsvsAZmt6YhNco',
    appId: '1:997210914530:web:71b77656347d9efafda8bb',
    messagingSenderId: '997210914530',
    projectId: 'teste-6de58',
    authDomain: 'teste-6de58.firebaseapp.com',
    databaseURL: 'https://teste-6de58-default-rtdb.firebaseio.com',
    storageBucket: 'teste-6de58.firebasestorage.app',
  );
}
